### ISSUE TITLE
Primary Key columns not going to the Topic

### ISSUE THREAD

**Issue by amticianelli** [averemee-si/oracdc#28]
Hello,

Firstly I would like to congrats you guys for this wonderful solution.

I'm having a problem when sending data which has a primary key to the topic, only the column with the primary key is not being sent.

Here is my conf files:

Oracle:
```sql
CREATE TABLE OWS.TABLE_TEST (
	ID INTEGER PRIMARY KEY,
	TEST1 VARCHAR2(10),
	TEST2 VARCHAR2(10),
	TEST3 VARCHAR2(10),
	TEST4 VARCHAR2(10)
);

alter table OWS.TABLE_TEST add supplemental log data (all) columns;

INSERT INTO OWS.TABLE_TEST VALUES (1,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (2,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (3,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (4,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (5,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (6,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
INSERT INTO OWS.TABLE_TEST VALUES (7,'Lorem ipsu','Lorem ipsu','Lorem ipsu','Lorem ipsu');
COMMIT;
```

Dockerfile:
```dockerfile
FROM quay.io/strimzi/kafka:latest-kafka-3.2.0
USER root:root

## Adding Confluent JDBC plugin 
RUN mkdir -p /opt/kafka/plugins/
RUN curl https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-jdbc/versions/10.5.1/confluentinc-kafka-connect-jdbc-10.5.1.zip --output /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-10.5.1.zip
RUN unzip /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-10.5.1.zip -d /opt/kafka/plugins/
RUN mv /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-10.5.1 /opt/kafka/plugins/confluentinc-kafka-jdbc
RUN rm -rf /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-10.5.1.zip
RUN curl https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.25/mysql-connector-java-5.1.25.jar --output /opt/kafka/plugins/confluentinc-kafka-jdbc/lib/mysql-connector-java-5.1.25.jar
RUN curl https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.25/mysql-connector-java-5.1.25.jar --output /opt/kafka/plugins/confluentinc-kafka-jdbc/mysql-connector-java-5.1.25.jar

## Adding OracleCDC Plugin
RUN curl https://d1i4a15mxbxib1.cloudfront.net/api/plugins/a2solutions/oracdc-kafka/versions/1.0.0/a2solutions-oracdc-kafka-1.0.0.zip --output /opt/kafka/plugins/a2solutions-oracdc-kafka-1.0.0.zip
RUN unzip /opt/kafka/plugins/a2solutions-oracdc-kafka-1.0.0.zip -d /opt/kafka/plugins/
RUN mv /opt/kafka/plugins/a2solutions-oracdc-kafka-1.0.0 /opt/kafka/plugins/a2solutions-oracdc-kafka
RUN rm -rf /opt/kafka/plugins/a2solutions-oracdc-kafka-1.0.0.zip

USER 1001
```

Kafka Connect:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: way4-poc
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
  readinessProbe:
    timeoutSeconds: 6000000
  livenessProbe:
    timeoutSeconds: 6000000
  image: amtiicanelli/ticianelli:kafka-connect-mysql-5
  template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
  replicas: 1
  bootstrapServers: strimzi-dev-kafka-bootstrap:9092
  config:
    group.id: my-connect-cluster
    offset.storage.topic: my-connect-cluster-offsets
    config.storage.topic: my-connect-cluster-configs
    status.storage.topic: my-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
```

Kafka Connect (Source connector):
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: oracdc-source-013
  namespace: way4-poc
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: solutions.a2.cdc.oracle.OraCdcLogMinerConnector
  tasksMax: 5
  config:
    a2.schema.type: kafka
    a2.poll.interval: 2000
    a2.batch.size: 10000
    a2.redo.size: 20000
    a2.resiliency.type: fault-tolerant
    a2.jdbc.url: jdbc:oracle:thin:@******:1521/*****
    a2.jdbc.username: ggsrc
    a2.jdbc.password: **********
    a2.include: 'OWS.TABLE_TEST'
    a2.initial.load: EXECUTE
```
When listing the topics:
```shell
kubectl exec -it strimzi-dev-kafka-0   -c kafka   -- bin/kafka-console-consumer.sh   --bootstrap-server strimzi-dev-kafka-bootstrap:9092   --topic TABLE_TEST   --from-beginning
```
`
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"TEST1"},{"type":"string","optional":true,"field":"TEST2"},{"type":"string","optional":true,"field":"TEST3"},{"type":"string","optional":true,"field":"TEST4"}],"optional":true,"name":"OWS.TABLE_TEST.Value","version":1},"payload":{"TEST1":"Lorem ipsu","TEST2":"Lorem ipsu","TEST3":"Lorem ipsu","TEST4":"Lorem ipsu"}}
`

The column ID is not showing, am I doing something wrong?

Thank you in advance, Alberto.

**Comment by averemee-si** [comment]
Salve Alberto,

Grazie mille per l'apprezzamento per il nostro lavoro!

When generating message in topic we're producing both key and value.
By default, the console consumer will show only the value of the Kafka record. You need to use additional options together with console consumer

```
kubectl exec -it strimzi-dev-kafka-0   -c kafka   -- bin/kafka-console-consumer.sh   --bootstrap-server strimzi-dev-kafka-bootstrap:9092   --topic TABLE_TEST  --property print.key=true --property print.value=true --from-beginning
```

Hope this helps.

Best regards,
Aleksei

**Comment by averemee-si** [comment]
Mea culpa!

Forget about one more property:

```
kubectl exec -it strimzi-dev-kafka-0   -c kafka   -- bin/kafka-console-consumer.sh   --bootstrap-server strimzi-dev-kafka-bootstrap:9092   --topic TABLE_TEST --formatter kafka.tools.DefaultMessageFormatter  --property print.key=true --property print.value=true --from-beginning
````

Best regards,
Aleksei

**Comment by amticianelli** [comment]
Hey Aleksei, thank you for the fast response!

It totally worked.

I changed the sink config from record_value to record_key and it worked like a charm:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: oracdc-sink-001
  namespace: way4-poc
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    connection.url: "jdbc:mysql://basic-tidb:4000/test"
    connection.user: root
    auto.create: true
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: "ID"
    #delete.enabled: true
    topics: TABLE_TEST
    auto.evolve: true
```
Thank you for giving me a better understanding about Kafka and the tool you are developing.

Grazie mille, Alberto.
